### PR TITLE
Add straight line support to routing

### PR DESCRIPTION
**Pull request by nrenner**
Adds client-side support for route segments to be straight lines ("as the crow flies") instead of requesting a route to follow ways. Part of #68.

### CODE REVIEW

**Comment by rkflx** [comment]
Nice work!

(Not sure why you already merged the PR less than 7 minutes after its creation, though. Are you not really interested in reviews or comments, and this is just for the CI checks? Personally, I won't spend too much review effort on this now it is already on master, since you were also asking previously to suspend reviews on the branch. I guess you'll want people to create new issues for minor individual bugs from here on, and consider the overall feature done.)

As for submitting and rebasing the various changes I hinted at before and which were waiting for the branch to merge: This will take me some time, sorry for that (busy currently).

Anyway, now it's time to celebrate one of the most requested features has been merged 🥳 🎉

Thanks!

**Comment by bagage** [comment]
Awesome work @nrenner, congrats for successfully landing that huge feature! And just in time for the summer :bike:  ;)

**Comment by nrenner** [comment]
> Not sure why you already merged the PR less than 7 minutes after its creation, though. 

I just wanted to get that out of the way. I personally like GitHub PRs as a nice overview of my larger changes, that might also be helpful for reference later on, instead of just merging, and they also make reviewing easier in case anyone feels like it, even if already merged.

**Comment by afischerdev** [comment]
Android works as well with the
`"lonlats"         = lon,lat,d|...`
variante.

**Comment by nrenner** [comment]
> As for submitting and rebasing the various changes I hinted at before and which were waiting for the branch to merge: This will take me some time, sorry for that (busy currently).

@rkflx Could you please list what those are, so we don't do duplicate work? E.g. #404 could be addressed now.

**Pull request merged**
