### PR TITLE
Move custom profile in sidebar

### PR DESCRIPTION
**Pull request by bagage**
Cf #66 todolist.

### CODE REVIEW

**Comment by nrenner** [comment]
Thanks for this so far. I should have explained more. What I meant was to add the profile as a separate tab (or whatever) like it was before, so that both profile and data table can then each on their own be shown in full screen height.

Some background: I keep postponing it, but my first goal for BRouter Web was to better support profile development and customization. Part of this would be providing some sort of IDE/editor using [CodeMirror](http://codemirror.net/) or similar, e.g. like [overpass turbo](http://overpass-turbo.eu/) or [Tangram Play](https://mapzen.com/tangram/play/).

Furthermore, being able to edit the routing profile at runtime is a distinctive feature of BRouter and I think it should be shown prominently. Also, people are often discussing what tags routers are supporting or which are preferred - another reason to raise awareness that to some extent they can see for themselves by looking at the profiles and for BRouter Web to provide an easy way to view and experiment with profiles. So to me the profile input field is more than just as small box to paste some profile text.

As for using tabs like before or something else, I increasingly think that using [sidebar-v2](https://github.com/Turbo87/sidebar-v2) instead might be an idea. Maybe on the right, with the layer switcher included, similar to osm.org, and maybe in flat instead of floating design and/or with a transparent bar background. But that might be for later.

**Comment by nrenner** [comment]
Addition to clarify:
All this is assuming that when no custom profile is active, the currently selected profile is shown. This is not working with brouter.damsy.net because of forbidden cross-origin requests and also needs to be [configured](https://github.com/nrenner/brouter-web/blob/master/config.js#L56-L61) when running locally.

**Comment by bagage** [comment]
I reconfigured properly (I think) my server. I am still using the default brouter instance, but now profiles are hosted on brouter.damsy.net so that they can be fetched. So the clarification issue is fixed :).
Still, I wasn't aware of your goals here: I'll redesign this PR a bit to better fit this purpose.

**Comment by nrenner** [comment]
> Still, I wasn't aware of your goals here

I briefly mentioned it in a [previous comment](https://github.com/nrenner/brouter-web/issues/34#issuecomment-245409552):

> [...] some other collapsible Sidebar will also do for the data table and for editing the profile.
> My original motivation for brouter-web was to build some kind of IDE for profile development and a planning tool with a focus on desktop.

The need for a different layout is also quite obvious when showing the currently selected profile, but I see how this feature can be overlooked, therefore the clarification.

**Comment by nrenner** [comment]
While you're at it, a related issue is scrolling, see #86.

**Comment by nrenner** [comment]
How do we go on with this PR? Shall we merge the current state or would you want to continue updating it?

**Comment by bagage** [comment]
Please merge as is and create a separate issue for the redesign? I think it will be a major update so I prefer to split it in 2 separate PRs.

**Pull request merged**
