### PR TITLE
Polish color coding + analysis tab visuals and fix a couple of related bugs

### PR DESCRIPTION
**Pull request by rkflx**
- Improve incline coding visuals and use different colors for going uphill
- Make hotline contrast more pleasant
- Improve analysis tab CSS
- Show analysis table highlight above quality coding layer

(See individual commit messages for a detailed discussion of the changes.)

Before:
before

After:
after

### CODE REVIEW

**Comment by nrenner** [comment]
Thanks for the detailed comments and separated commits!

> Improve incline coding visuals and use different colors for going uphill

Very nice improvement!

Looks good to me overall.

@mjaschen do you want to review 8ca92e26?

**Comment by mjaschen** [comment]
Yes, of course – I’ll take a look at it in the morning :-)

**Comment by mjaschen** [comment]
I really like the changes introduced with 8ca92e2 – the tables/headers look much cleaner now, thanks for tidying up @rkflx :-)

**Comment by nrenner** [comment]
Thanks for the contribution!

**Pull request merged**
