### PR TITLE
 Exporting to FIT #322

### PR DESCRIPTION
**Pull request by tbsmark86**
I've finally (after some failed runs ...) had a successful test ride (9km, 11 turns) with correct turn instructions on my wahoo bolt (old version) today.

* Tip: You can use https://www.fitfileviewer.com/  to view the content
* The 3 patch is not required for this I've just stumbled upon this problem while searching for the distance value of the turn markers ... before realizing this is distance-to-next and not the distance-from-last that I needed :)

### CODE REVIEW

**Comment by tbsmark86** [comment]
About this build error: gulp uglify complains about the es6 code in the ne fit-file-writer lib.
However if i move the code from node_modules/... to js/export/ it does not complain??

I've never used gulp before any tips? Or do I have to rewrite the lib to use es5?

**Comment by tbsmark86** [comment]
force push to fix the build error

**Review by nrenner — CHANGES_REQUESTED** [review]
Thanks for the PR!

> The 3 patch is not required for this I've just stumbled upon this problem while searching for the distance value of the turn markers ... before realizing this is distance-to-next and not the distance-from-last that I needed :)

Thanks for the fix. Your "distance-from-last" comment got me confused, as I understand this fixes distance-to-end-of-segment instead of distance-to-next?

However, my primary focus for client-side formatting so far was to produce largely the same results as the brouter server/app. So `voicehints` of the expected test result [brouterTotal.json](https://raw.githubusercontent.com/nrenner/brouter-web/master/tests/control/data/brouterTotal.json) should match the [total download](https://brouter.de/brouter?lonlats=8.467712,49.488117|8.469354,49.488394|8.470556,49.488946|8.469982,49.489176&profile=trekking&alternativeidx=0&format=geojson&profile:turnInstructionMode=2) from the server (for [this route](https://brouter.de/brouter-web/#map=18/49.48856/8.46986/standard&lonlats=8.467712,49.488117;8.469354,49.488394;8.470556,49.488946;8.469982,49.489176)).

I would appreciate if you could move the third commit 54bf446 to a separate PR, as I'm not sure if we should wait until the pending server-side PR is merged that supposedly also fixes this.

**Comment by tbsmark86** [comment]
Ok. I removed the third commit - extra pull request incoming soon.

**Review by nrenner — APPROVED** [review]

**Comment by nrenner** [comment]
Thanks for your contribution!

**Pull request merged**
