### PR TITLE
Route Loader Keyboard Shortcut

### PR DESCRIPTION
**Pull request by mjaschen**
This pull request enables opening the “import as route” by pressing `r` (for “route”) on the keyboard.

Additionally, an unused option value is removed from the `cleanup()` method.

### CODE REVIEW

**Comment by rkflx** [comment]
Did you test for shortcut conflicts?

Any tooltip changes needed?

**Comment by rkflx** [comment]
> Any tooltip changes needed?

BTW, tooltips in the top bar might be broken currently, possibly due to 5b52abc1.

**Comment by bagage** [comment]
Good catch @rkflx, I pushed a fix https://github.com/nrenner/brouter-web/commit/17bbef17bdc0f824e9d316fe7f36896ac4823e65 for that, thanks!

**Comment by mjaschen** [comment]
> Did you test for shortcut conflicts?

Yes, but after a second check I noticed, that `r` is indeed already used for `reverse route` 🤦‍♂️  I didn't notice that, because importing a track as route is usually done without an existing route (which means that pressing `r` has no effect in this case). Thanks for pointing this out.

My next proposal would have been `Shift-O` but this shortcut is already used (“import no-go area”)

The list of all keyboard shortcuts which are currently defined (maybe also a good topic for the upcoming documentation efforts):

|Shortcut|Description|
|:-:|---|
| `D` | enter draw mode |
| `Esc` | exit draw mode or close dialog |
| `Z` | remove last point from route (“undo”) |
| `M` | hide route temporarily (as long as key is down) |
| `P` | insert „Point of Interest“ (`Esc` exists this mode) |
| `+`, `-` | zoom map |
| `←`, `→`, `↓`, `↑` | move map |
| `L` | center current position (geolocation browser-feature) |
| `F` | search for locations |
| `R` | reverse route |
| `N` | draw „No Go Area“ |
| `Backspace` | delete route |
| `C` | toggle through color-coding modes |
| `S` | activate/deactivate Strava layer (if configured) |
| `E` | show elevation profile |
| `G` | switch routing profile |
| `X` | export route |
| `O` | load track |
| `Shift-O` | load “No Go Area” |
| `H` | show “About” dialog |
| `T` | toggle sidebar |
| `Shift-T` | switch tabs in sidebar |
| `I` | draw allowed zone |

New ideas for the “import as route” shortcut: `Shift-R` or `U`. Maybe there are other suggestions?

**Comment by rkflx** [comment]
> New ideas for the “import as route” shortcut: `Shift-R` or `U`.

How about `N` and `Shift+N` for draw/load „No Go Area“, so we could have `O` and `Shift+O` for „Import as Track/Route“ respectively?

---

> Good catch @rkflx, I pushed a fix 17bbef1 for that, thanks!

Thanks @bagage!

**Comment by mjaschen** [comment]
> How about N and Shift+N for draw/load „No Go Area“, so we could have O and Shift+O for „Import as Track/Route“ respectively?

+1

I'd like that. Maybe apart from the fact, that we've to change an established shortcut. But I personally wouldn't mind to do such a change 🤷🏻 

@nrenner do you have an opinion on this?

**Comment by nrenner** [comment]
It would be a good improvement, so I guess the change is justified.

**Comment by mjaschen** [comment]
Great! I'll update the pull request.

**Comment by mjaschen** [comment]
Shortcuts/tooltips were updated. 

Updated keyboard shortcuts overview:

|Shortcut|Description|
|:-:|---|
| `D` | enter draw mode |
| `Esc` | exit draw mode or close dialog |
| `Z` | remove last point from route (“undo”) |
| `M` | hide route temporarily (as long as key is down) |
| `P` | insert „Point of Interest“ (`Esc` exists this mode) |
| `+`, `-` | zoom map |
| `←`, `→`, `↓`, `↑` | move map |
| `L` | center current position (geolocation browser-feature) |
| `F` | search for locations |
| `R` | reverse route |
| `N` | draw „No Go Area“ (`Esc` exists this mode) |
| `Shift-N` | load “No Go Area” |
| `Backspace` | delete route |
| `C` | toggle through color-coding modes |
| `S` | activate/deactivate Strava layer (if configured) |
| `E` | show elevation profile |
| `G` | switch routing profile |
| `X` | export route |
| `O` | load track |
| `Shift-O` | load track as route |
| `H` | show “About” dialog |
| `T` | toggle sidebar |
| `Shift-T` | switch tabs in sidebar |
| `I` | draw allowed zone |

**Comment by nrenner** [comment]
Thanks!

**Comment by nrenner** [comment]
I added the overview to the wiki:
https://github.com/nrenner/brouter-web/wiki/Keyboard-shortcuts

**Pull request merged**
