### PR TITLE
Use leaflet.restoreview.js plugin to save and restore last user's map…

### PR DESCRIPTION
**Pull request by bagage**
… position between sessions (#48)

I am not JS developer so please tell me if something is wrong with my PR. Thanks @nrenner!

### CODE REVIEW

**Comment by bagage** [comment]
Added another patch for 2nd part of #48. I added reference to Awesome font in `index.html`, but maybe you wish not to use it?
Again any comment's welcome, I am a truly newbie here!

**Comment by nrenner** [comment]
Thanks for the PR! I do have comments, but don't worry, still learning myself. And I should have more documentation.

The build setup using Bower and Gulp is still a bit rough and not ideal. Also already outdated again, as people seem to have moved on to Webpack nowadays. But what I'm trying to achieve is that all dependencies are referenced and downloaded through Bower, so that the origin and the version used are documented and that managing and updating the depencencies gets a bit easier.

**leaflet.restoreview:**

I would prefer ``js/plugin/leaflet.restoreview.js`` to be added and downloaded via Bower although its an overhead in this case. The dir name ``plugin`` is a bit misleading here, intended for own configuration and extension of external plugins only. 

As it has no bower.json and is not registered with bower (https://bower.io/search/), I think you can reference the repo and add it to the bower.json with 

    bower install makinacorpus/Leaflet.RestoreView#master --save

Then add the file to include (leaflet.restoreview.js) to the "overrides" section. Check if included with ``gulp debug``.

**leaflet.locatecontrol**

Yes, I would prefer not to load another fontset, as we already have [Glyphicons](http://getbootstrap.com/components/#glyphicons) from Bootstrap, but Glyphicons is a bit limited and seems not to have a spinner. Not sure about the marker icon, maybe [fa-location-arrow](http://fontawesome.io/icon/location-arrow/) or something similar to ``glyphicon glyphicon-screenshot`` (but more GPSy) instead, what do you think?

But I might as well merge the commit as it is and think about that later, as I want to add more icons anyway and am not decided on the icon-/fontset yet.

**Comment by bagage** [comment]
Thanks! 

- [x] I moved leaflet.restoreview to bower 
- [x] I removed Awesome font dependency and instead use `glyphicon-refresh` and `glyphicon-screenshot` icons instead. They are not perfect but I guess it's OK for now. I also added overrides for `locatecontrol` plugin but I am unsure about it; could you take a look at it please?

**Comment by nrenner** [comment]
Thanks for the update. Yes, the icons will do for now.

The bower override for locatecontrol isn't necessary, as the project already has a bower.json with a proper [main section](https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/bower.json#L9-L12).

Could you please remove that again, then I think we're ready to merge.

**Comment by bagage** [comment]
OK I removed it, I can't wait to use these on brouter-web! :smile:

**Pull request merged**
