### PR TITLE
WIP: Add PWA/TWA required files

### PR DESCRIPTION
**Pull request by bagage**
This aims to make BRouter a [Progressive Web App](https://web.dev/progressive-web-apps/) (PWA) and [Trusted Web App](https://developers.google.com/web/android/trusted-web-activity/quick-start) (TWA).

There are various things to finalize:

- mobile version could be improved (#296), not mandatory
- have a proper logo (#286). For now and test purposes, I'm using my placeholder. The maskable icon was made with https://web.dev/maskable-icon/
- define BRouter [theme](https://developer.mozilla.org/en-US/docs/Web/Manifest/theme_color) and [background](https://developer.mozilla.org/en-US/docs/Web/Manifest/background_color) colors. For now I've set both to `#343a40`.
- I deployed `manifest.json` and `.well-known/assetlinks.json` to my instance. You can try TWA from [this APK](https://gitlab.com/bagage/brouter-web/uploads/a03409ed428fbfd112931a89be7d90cf/BRouter.apk) (generated via https://www.pwabuilder.com/publish)
- the best (I think) solution would be to integrate the TWA directly into the existing BRouter application. But a separate app can be used too (you only have to update `assetlinks.json` accordingly)
- to generate the APK, you can use pwabuilder.com but I believe it's better to use `bubblewrap` directly and commit required files in brouter or brouter-web repository
- some files might be removed from the repository, or not, I'm unsure yet.

### CODE REVIEW

**Comment by nrenner** [comment]
> This aims to make BRouter a Progressive Web App (PWA) and Trusted Web App (TWA).

When you write "BRouter" in the description and also in the manifest, that should probably be "BRouter-Web"?

I have a rough idea what a PWA is, but I'm not familiar yet with TWA. So a PWA can install on the home screen but not go full screen, for that you need a TWA installed as an APK?

> You can try TWA from this APK 

That link doesn't work.

> mobile version could be improved (#298), not mandatory

You proabably mean #296?

> the best (I think) solution would be to integrate the TWA directly into the existing BRouter application.

What files would need to be integrated there, would that be a one-time thing or for every BRouter-Web release? Do we need a separate icon when using a single APK?

Do all those files need to be in the root folder? We already have too many files in the project root and I would prefer to put anything that doesn't need to be there into some subfolder, e.g. the images into a `resources` subfolder.

**Comment by bagage** [comment]
> When you write "BRouter" in the description and also in the manifest, that should probably be "BRouter-Web"?

Yes indeed. Will rename it accordingly.
> 
> I have a rough idea what a PWA is, but I'm not familiar yet with TWA. So a PWA can install on the home screen but not go full screen, for that you need a TWA installed as an APK?

I think there are 2 main differences:
- a TWA can be published on the play store or alternative apps markets, so you can have a "native experience" with the app.
- PWA/TWA are webviews, so it's basically Chrome or Firefox which run underneath. If you use a TWA, the browser navigation bar is hidden, allowing to gain some height space:

diff

> 
> > You can try TWA from this APK
> 
> That link doesn't work.

Indeed, my bad. [Here it is](https://gitlab.com/bagage/brouter-web/uploads/a03409ed428fbfd112931a89be7d90cf/BRouter.apk).
> 
> > mobile version could be improved (#298), not mandatory
> 
> You proabably mean #296?


Yes indeed.

> 
> > the best (I think) solution would be to integrate the TWA directly into the existing BRouter application.
> 
> What files would need to be integrated there, would that be a one-time thing or for every BRouter-Web release? Do we need a separate icon when using a single APK?

The APK can be (re)generated from the `manifest.json` (which itself links to icons that must be accessible online). Rebuilding the APK is only required when the manifest and/or icons change. Otherwise the APK is basically a webview pointing to the website, so whenever a new BRouter-web release is deployed, the APK is just up-to-date as well.

> 
> Do all those files need to be in the root folder? We already have too many files in the project root and I would prefer to put anything that doesn't need to be there into some subfolder, e.g. the images into a `resources` subfolder.

No they can be put elsewhere. Some have to be embedded in Brouter releases (`pwabuilder-sw.js`, maybe `favicon.ico`), the others can be put in a separate `resources` subfolder.

**Comment by mjaschen** [comment]
There are some hardcoded things (namespace/fingerprint) in `assetlinks.json`. 

What does that mean for BRouter-Web instances which are deployed elsewhere?

**Comment by bagage** [comment]
@mjaschen I'm not 100% sure about all PWA related stuff, but from what I understand:

`assetlinks.json` is meant to be deployed on websites ([here](https://brouter.damsy.net/.well-known/assetlinks.json) for my instance). It lists apps that are trusted for this website, eg. any APK with identifier `net.damsy.brouter` and signed with `9F:...:D1` (which is the APK I generated above) hash signature is a trusted app (the only consequence I know is that the browser nagivation bar is hidden). 
But if you do not deploy `assetlinks.json` on your website and/or if you remove that entry from the file, then my APK won't be trusted on your instance and thus it will simply be a PWA. You can list many apps in that file - but this file could also be out of brouter repository, I don't know best practice about that yet.

**Comment by nrenner** [comment]
>  If you use a TWA, the browser navigation bar is hidden, allowing to gain some height space

Doesn't the `"display": "standalone"` or `fullscreen` in the PWA manifest already do that (without TWA)?
https://web.dev/add-manifest/#display

**Comment by bagage** [comment]
From my tests, at least with Firefox, it does not hide the navigation bar without TWA, but I might be missing something.

**Comment by Phyks** [comment]
> From my tests, at least with Firefox, it does not hide the navigation bar without TWA, but I might be missing something.

As far as I know, Firefox support for PWA can be quite limited on Android devices. Sadly, Chrome should be better for tests here.

**Review by bueltge — APPROVED** [review]
Would be really helpful for the mobile usage.

**Comment by bueltge** [comment]
@bagage Great!
Would you add an option to change the static strings inside the manifest.json dynamically for deployment?
Hint https://stackoverflow.com/questions/50086761/dynamic-icon-pwa-manifest

**Comment by bagage** [comment]
Closing this as I don't plan to finish it anytime soon.

**Pull request closed without merging**
