### PR TITLE
Feature/color route segments

### PR DESCRIPTION
**Pull request by matzepan**
Added a overlay which reflects the quality of the route based on either:
* cost
* altitude
* incline
Partially adresses https://github.com/nrenner/brouter-web/issues/19 and could be extended by using https://github.com/hgoebl/Leaflet.MultiOptionsPolyline to overlay the road types.

### CODE REVIEW

**Comment by bagage** [comment]
I didn't looked at the code yet and wanted to give it a try, looks also good! I'm not sure if `cost` should be the default one (over incline), but 3 visualizations are complementary.

The coloration doesn't go away when you refresh route (eg. if you switch between profile, you end up with the old colored profile and the new pink profile, until the route is fully calculated). Is that a bug or a feature?

Capture d’écran vidéo de 01-10-2019 19:48:24_cropped

**Comment by matzepan** [comment]
@bagage this is just the way components get notified when a total reloading of the track is done. Like the elevation chart.
But you're right the cost function currently might be most useful for me because I want to see where the algorithm shows the most costly paths. I changed it to be incline first.

Next thing would be to maybe switch to https://github.com/hgoebl/Leaflet.MultiOptionsPolyline and get this to a separate tab to the right similar to:
image

**Comment by Phyks** [comment]
> Next thing would be to maybe switch to https://github.com/hgoebl/Leaflet.MultiOptionsPolyline and get this to a separate tab to the right similar to

There was the idea to have a separate tab for BRouter-web configuration (for instance for #229). Maybe this would be a good place to put the options for the path overlay color as well?

**Comment by matzepan** [comment]
@bagage can we switch to gulp-uglify-es to support ecmascript 6?

**Comment by bagage** [comment]
Totally that would be cool! Is there any reason not to @nrenner?

**Comment by nrenner** [comment]
I opened a new issue for the ES 6 question: #249.

Great to see many pull requests! Will try to look through them in the next days.

**Comment by nrenner** [comment]
Nice! I do have some comments, but will open a follow-up issue after merging.

Just a minor wish right now: can we move the button just above the route [opacity slider](https://github.com/nrenner/brouter-web/blob/90dfa5b7f33054e61ae258e98188eac46954b4a3/js/index.js#L276) (by moving the `.addTo(map)`)? It's less important than the `drawToolbar` and fits thematically, as both change the route appearance.

**Comment by nrenner** [comment]
Thanks!

**Comment by nrenner** [comment]
A follow-up issue: #262

**Pull request merged**
