### PR TITLE
Add strava layer in overlays

### PR DESCRIPTION
**Pull request by bagage**
So that user can show/hide at will.

### CODE REVIEW

**Comment by nrenner** [comment]
Thanks, the plugin improvements seem to address my concerns, planning to add a key with the next release.

**Comment by bagage** [comment]
That's great! I plan to review my work branch to see what are the remaining diff between our hosted versions, merge last pieces and probably shut it down.

* The main difference I see right now is #87, eg add HTTPS support on brouter.de. 
* Also some custom profiles I've added (trekking-no-path, mtb and mtb-avoid-road) that are not available on brouter.de instance, but maybe they can be added directly? Or it'll need work on custom profiles (#97 #24)
* The profiles are displayed a bit differently, but this is not a major feature and can be dropped if needed.

**Comment by nrenner** [comment]
> Also some custom profiles I've added (trekking-no-path, mtb and mtb-avoid-road) that are not available on brouter.de instance, but maybe they can be added directly?

Please also open an issue for those to add on abrensch/brouter.

I'm a bit sceptical about offering MTB profiles as riding single-trails in forests is illegal in the part of Germany where I live.

> The profiles are displayed a bit differently, but this is not a major feature and can be dropped if needed.

I think what we really want here is making the profile list translatable. I wanted to wait with translations until the app is more feature-complete and mature, but maybe we could register and setup Transifex and start with translating the profile names.

My current priority is offering additional tile layers though (#145 #146). Improving custom profile handling hopefully next.

**Comment by bagage** [comment]
> Please also open an issue for those to add on abrensch/brouter.
OK, did it in https://github.com/abrensch/brouter/issues/141

> I think what we really want here is making the profile list translatable. [...]
Sounds good. Then my "hack" is not needed anymore. Did you investigate i18n yet since https://github.com/nrenner/brouter-web/issues/63? If you know a way to do it, I might invest some time in it.

**Comment by nrenner** [comment]
No, I haven't. Just collected [these two links](https://github.com/nrenner/brouter-web/issues/63#issuecomment-457679565) on the topic.

**Comment by nrenner** [comment]
I can look into applying for a free account on Transifex and maybe becoming a member of the OpenStreetMap group.

**Comment by nrenner** [comment]
>> I think what we really want here is making the profile list translatable. [...]

> Sounds good. Then my "hack" is not needed anymore.

From a quick look it seems Transifex is using a primary language (English in our case) as the lookup key for the translate function. Don't know how this will work with the profile list, we might still need some sort of mapping from the current profile name to the English display name.

**Pull request merged**
