### PR TITLE
Allow user to add custom layers

### PR DESCRIPTION
**Pull request by bagage**
This would solve #73 but also my issue, eg. a French (super)great TMS which is for "single user" access only, so we cannot add it to Brouter but as a user I can :).

image

### CODE REVIEW

**Comment by krisanselmo** [comment]
Nice feature, thanks! 
The use of strava heatmap overlay may be very useful (according to me) for hike or ride routing.
[https://wiki.openstreetmap.org/wiki/Strava](https://wiki.openstreetmap.org/wiki/Strava)
I can't wait to test :)

**Comment by bagage** [comment]
@krisanselmo you can give it a shot on http://brouter.damsy.net 
Any feedback appreciated!

**Comment by nrenner** [comment]
Very nice addition! Indeed useful for regional, personal-use-only (German agencies also have these) and other not included maps.

Not relevant for merging, but what do you think about adding the button inside the layer switcher (e.g. just a [quick hack](http://playground-leaflet.rhcloud.com/fole/edit?html,output))? I feel we should rather reduce the number of buttons on the map if not needed in daily use.

If you wanted, I guess it might even make sense to turn this into a [Leaflet plugin](http://leafletjs.com/plugins.html#develop-your-own).

**Comment by nrenner** [comment]
@krisanselmo I added the Strava heatmap to my todo list of potential layers to add. Would need to check the terms of use. I'm generally open for map suggestions, but would want to avoid having too many layers in the list.

**Comment by bagage** [comment]
> Not relevant for merging, but what do you think about adding the button inside the layer switcher (e.g. just a quick hack)? I feel we should rather reduce the number of buttons on the map if not needed in daily use.
Yeah sure it sounds good. Small fix first, the button should have `type=button` to [avoid submitting POST on click](http://stackoverflow.com/questions/2825856/html-button-to-not-submit-form). But besides that, the proposed hack cannot work as is because [leaflet is iterating over `input` children](https://github.com/Leaflet/Leaflet/blob/cbaf02034c916e0e3ea1f1f5c21d08c41efd0b3e/src/control/Control.Layers.js#L393-L402). Do you know how to workaround this too @nrenner?

**Comment by nrenner** [comment]
> Small fix first, the button should have type=button to avoid submitting POST on click.

Thanks for the hint.

> But besides that, the proposed hack cannot work as is because leaflet is iterating over input children.

Good catch, but would it matter if it stays `button type=button`, instead of `input type=button`? Or maybe using a styled link (`a href="#"`, with [`preventDefault`](http://leafletjs.com/reference-1.0.3.html#domevent-preventdefault) or `stop`), see Bootstrap [Button tags](http://getbootstrap.com/css/#buttons-tags).

Generally the hack was really just that, and more for me to see if adding a button would work at all and to show what I meant, not how to do it. There probably are better ways, perhaps none of them ideal. I haven't looked deeper, just saw that `layerSwitcher.getContainer().innerHTML += '...'` (or better `appendChild`) didn't work right away, because the button would still be shown when collapsed.

**Comment by nrenner** [comment]
Merged this now and created a separate issue for moving the button into the layer switcher: #89

**Pull request merged**
