### PR TITLE
Usability fix: Allow Return Key in export dialog

### PR DESCRIPTION
**Pull request by tbsmark86**
very simple but anoying for a keyboard user :)

### CODE REVIEW

**Comment by bagage** [comment]
Thanks :)

**Comment by rkflx** [comment]
This was one of the annoying things I did not yet get around to tackle when working on #314. Thanks for trying to fix this!

However, it does not work in Chromium for me, where it even breaks for mouse users: Starting at an URL with an empty query component, clicking "Export route" in the export dialog redirects to `/?format=gpx#...`.

(In Firefox the issue does not manifest itself, since there the `/?format=gpx` request is listed as "blocked".)

**Comment by nrenner** [comment]
I added a `event.preventDefault()` to stop the default submit action and it seems to fix the download and `?format=gpx` URL query in Chromium.

Don't know why the return key does not work in Chromium. From a quick search the criteria for implicit submission is a `form` tag and non-submit buttons having a `type="button"` attribute which both seems to be the case.

**Comment by rkflx** [comment]
@nrenner Thanks, working great now.

**Pull request merged**
