### PR TITLE
Feature/load gpx track

### PR DESCRIPTION
**Pull request by matzepan**
Added the ability to load tracks (kml, gpx, geojson, json) using leaflet-filelayer and display them as new Overlay layer.
Addresses: https://github.com/nrenner/brouter-web/issues/30

### CODE REVIEW

**Comment by bagage** [comment]
Hey @matzepan, welcome aboard! Thanks for your contribution, it is one of the most asked-for feature. From what I've seen it's looking good, albeit a *minor* issue: it looks like tracks are declared as interactive layers but it seems they are not:

Capture d’écran vidéo de 01-10-2019 19:27:32_cropped

Good work!

**Comment by matzepan** [comment]
@bagage this is also a feature that I wanted badly.
I changed the loaded track to be not interactive.
Thank you for your feedback.

**Comment by Phyks** [comment]
What about keeping the loaded track in a URL parameter for easy sharing of the full view? For instance by encoding the polyline with `mapbox/polyline` in a `track` (`tracks`?) GET parameter similarly to https://github.com/nrenner/brouter-web/pull/233 (which I should finish by the way)?

**Comment by matzepan** [comment]
@Phyks I don't know if it makes sense to put these into the URL. Especially if this means blowing up the URL length.

**Comment by Phyks** [comment]
It makes sense to have it to easy share the view with someone else / another computer. But indeed it probably does not make sense to have it in the URL and risk blowing the URL length.

Maybe BRouter-web should have something like Overpass to shorten links and share easily (including custom profiles, etc).

**Comment by nrenner** [comment]
Great contribution, thanks!

**Pull request merged**
