### PR TITLE
Use Heightgraph in lieu of Elevation to show the elevation profile

### PR DESCRIPTION
**Pull request by alexcojocaru**
Things to note:
* d3 3.x was used only by Elevation, I removed both from the project dependencies;
  that is because Heightgraph only works with d3 5.x, whereas this project
  used d3 3.x;
* Since Heightgraph is written with ES6 (as is d3 5.x I believe),
  I had to use its transpiled bundle (which includes d3 5.x);
* There were a few definitions in the transpiled Heightgraph which conflicted
  with the rest of brouter-web; I had to comment them out via a patch
  applied in the postinstall phase.

This PR is related to https://github.com/nrenner/brouter-web/issues/343;
since I used the transpiled Heightgraph, the upgrade to d3 5.x is not necessary.

### CODE REVIEW

**Review by nrenner — CHANGES_REQUESTED** [review]
Thanks for working on this!

Some issues:
1. Leaflet.Heightgraph and the plugin wrapper Heightgraph.js don't seem to handle missing elevation data:
   - `TypeError: Cannot read property 'text' of  undefined  at NewClass._prepareData (L.Control. Heightgraph.js:4994)`
     - http://localhost:3000/index.html#map=12/53.5235/8.5705/osm-mapnik-german_style&lonlats=8.545475,53.520411;8.565903,53.529595;8.584442,53.538267&profile=fastbike
   - `TypeError: Cannot read property 'geometry' of  undefined  at Heightgraph.js:267`
     - http://localhost:3000/index.html#map=17/44.44707/15.18322/standard&lonlats=15.183293,44.447082;15.181603,44.448656&profile=fastbike
     - http://localhost:3000/index.html#map=12/59.9929/5.4975/Stamen.Terrain&lonlats=5.51033,60.028328;5.506211,59.9679
   - see issues abrensch/brouter#137, #203 and  [Leaflet.Elevation#63 (comment)](https://github.com/MrMufflon/Leaflet.Elevation/issues/63#issuecomment-581027804)
2. collapsed state is not remembered for the next session 
   - this is due to missing `initCollapse` method and it's call in `index.js`
3. missing bottom tiles after resizing window and closing height graph
   - `map._onResize();` call after collapse missing, also in `initCollapse` method
4. applying a patch to a distribution bundle is a bit fragile and will probably fail (need maintenance) with some future update
   - wrapping the bundle inside a closure using an  IIFE (immediately invoked function expression),  so d3 doesn't pollute the global scope, seems to  work as well:
     ```
     (function() {
       ...
     }());
     ```
     Automatically adding those lines at the top and bottom of the bundle file would be less fragile, so I would prefer that instead of the patch, if there is a way

**Comment by alexcojocaru** [comment]
Thanks for looking at this, @nrenner . I will have a look at issues 1 through 3 and fix them.

About 4 (patching the Heightgraph bundle): 
* I set a fixed Heightgraph version in package.json, which shouldn't break the patch unless the Heightgraph dependency is explicitly updated, but I agree that this patch is fragile and it would probably have to be redone when switching to newer versions of the dependency, so it's just a temporary solution
* there's [this discussion](https://github.com/GIScience/Leaflet.Heightgraph/issues/101) which I started on the Heightgraph project, where I asked if it's possible to wrap the whole code in the bundle; given there hasn't been much feedback, I expect the worst (i.e. not going to happen any time soon, if any)
* do you know if it's possible to modify the patch to apply the IIFE? that would make it more resilient to further changes to the Heightgraph bundle; if so, wouldn't there be issues with extending Heightgraph [here](https://github.com/nrenner/brouter-web/pull/345/files#diff-781f92da3be7c52bcdf8bd0d836ae292a1f35798a78b24309d5290706f6c3adcR2) ?

**Comment by nrenner** [comment]
> it looks like I can modify the patch to apply the IIFE [...] does this sound like an acceptable solution for the time being?

I guess that would already be an improvement and maybe easier to check if the patch is still ok.

I intend to open separate/new Heightgraph issues for 1. and 4.

**Comment by nrenner** [comment]
What I have in mind is the same approach I implemented for Leaflet.Elevation in PR MrMufflon/Leaflet.Elevation#84 (we're using my fork).

Leaflet.Heightgraph should support `undefined`/`null` values for all or part of the elevation values and show them as gap in the graph using a d3 [defined](https://github.com/d3/d3-shape/blob/master/README.md#area_defined) accessor function.

**Comment by nrenner** [comment]
I opened an issue for 4.:  GIScience/Leaflet.Heightgraph#107.

The minified bundle has an IIFE, so we might just use that for now, but for some reason it didn't get included when I had a quick try changing the main reference to it.

**Comment by alexcojocaru** [comment]
> The minified bundle has an IIFE, so we might just use that for now, but for some reason it didn't get included when I had a quick try changing the main reference to it.
It's not obvious why, all I can say is that the Heightgraph attribute is not available in that scope.

I have been working on handling points with `undefined` altitude coordinate without errorring out, as there is some manipulation of such points in the plugin. Once that is done, I will look at issues #2 and #3 you described earlier.

**Comment by alexcojocaru** [comment]
A short update on the progress:
1. Missing elevation data: the code in Heightgraph.js can handle such points without breaking; I have tested many edge cases and it works as expected. Leaflet.Heightgraph has to be fixed to deal with such point on its end though.
2-3. My bad on ignoring some of the code in Elevation.js (resize, collapse/expand, etc). I worked on an old version of your project and did not notice these improvement, nor they conflicted with my changes (since Elevation.js is removed in my branch).
4. The patch was updated to use an IIFE. Still couldn't get the minified Heightgraph to work.

**Comment by alexcojocaru** [comment]
Just finished fixing items 2 and 3.

To summarize: the only outstanding issue currently is in Leaflet.Heightgraph, when the track contains points without elevation data. Given the recent activity on that project (or the lack thereof), I am not too optimistic about it being fixed soon.

**Comment by alexcojocaru** [comment]
Like I said in the previous comment, I have the feeling that the bug in Leaflet.Heightgraph around handling points without elevation would take quite a while to get fixed. Because of this, I handled such points in the Heightgraph plugin and inferred their elevation from the closest points with elevation in the track: https://github.com/nrenner/brouter-web/pull/345/commits/d83fddd4edcbf3abcfb68d822102549099fa0f43

Speaking of this bug in Leaflet.Heightgraph, since you fixed the similar one in Leaflet.Elevation and you have more context, could you open an issue for it please? Thanks.

**Comment by nrenner** [comment]
Thanks for the updates.

I'm not sure about interpolating missing elevation values. While interpolation might work for some cases, it will be misleading or just wrong for others. I personally consider showing the data as it is - with gaps in the graph for missing values - as the proper solution, which is why I implemented this for Leaflet.Elevation. Switching to Heightgraph without this feature feels like a step back in this regard.

I have opened an issue for missing elevation data: [Heightgraph#108](https://github.com/GIScience/Leaflet.Heightgraph/issues/108). And I will look into making a PR for this.

**Comment by alexcojocaru** [comment]
👍  to your statement. Undoing it is easy, I just have to revert the last commit.
Looking forward to having the Heightgraph issue fixed...

**Review by nrenner — APPROVED** [review]
Thanks for your contribution!

**Comment by alexcojocaru** [comment]
Thanks for integrating this change, I look forward to using it.

My impression was that the major blocker to using Heightgraph was its inability to handle tracks with points with undefined elevation. I see that you [fixed it](https://github.com/GIScience/Leaflet.Heightgraph/pull/110), and the IIFE issue as well, but the PRs were not merged in.

**Pull request merged**
